{% set name = "icclim" %}
{% set version = "5.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/icclim-{{ version }}.tar.gz
  sha256: 3386c8875a513c6665cb324e8c75667ab6ba7174222bd68ccbde1d9ed57ed896

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - cftime
    - dask
    - netCDF4
    - numpy
    - pyyaml
    - xarray
    - xclim >=0.37
    - rechunker >=0.3, !=0.4
    - pandas >=1.3
    - dateparser
    - psutil
    - fsspec

test:
  requires:
    - pip
  imports:
    - icclim
    - icclim.models
  commands:
    - pip check

about:
  summary: 'icclim (Index Calculation CLIMate) is a python library for climate indices calculation.'
  home: https://github.com/cerfacs-globc/icclim
  doc_url: https://icclim.readthedocs.io/
  dev_url: https://github.com/cerfacs-globc/icclim
  license: Apache-2.0
  license_file: LICENSE
  description: |
    icclim (Index Calculation CLIMate) is a python library for climate indices calculation.
    It wraps xclim, xarray and dask in a staight forward API. It is first meant to compute
    the ECA&D indices but also provide an API to create customized indices based on a few operators.

extra:
  recipe-maintainers:
    - pagecp
    - bzah
